name: Fetch responses and create resources

# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
on:
    workflow_dispatch

jobs:
    update:
        name: Update data
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                node-version: 12.x
            - run: npm install
            - run: node fetch-form-responses.js
              env:
                RESPONSES_SPREADSHEET_ID: ${{ secrets.RESPONSES_SPREADSHEET_ID }}
                READER_CREDENTIALS: ${{ secrets.READER_CREDENTIALS }}
            - run: node create-resources-from-responses.js
            - name: Push changes
              run: |
                git config user.name ${{ github.actor }}
                git commit -a -m "Update resources from Sheets"
                git push
